apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
type: Opaque
stringData:
  # Fixed passwords for development
  elastic-password: "deuknet2024"
  kibana-password: "deuknet2024"
  logstash-password: "deuknet2024"
  logstash-writer-password: "deuknet2024"
  filebeat-password: "deuknet2024"
