apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200        # 클러스터 내부 접근 포트
      targetPort: 9200
  type: ClusterIP
