{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.elasticsearch.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  elastic-password: {{ .Values.elasticsearch.env.elasticPassword | quote }}
  kibana-password: {{ .Values.elasticsearch.env.elasticPassword | quote }}
  logstash-password: {{ .Values.elasticsearch.env.elasticPassword | quote }}
  logstash-writer-password: {{ .Values.elasticsearch.env.elasticPassword | quote }}
  filebeat-password: {{ .Values.elasticsearch.env.elasticPassword | quote }}
{{- end }}
