{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.elasticsearch.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.httpPort }}
      targetPort: {{ .Values.elasticsearch.service.httpPort }}
      protocol: TCP
  type: {{ .Values.elasticsearch.service.type }}
{{- end }}
