{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.filebeat.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.filebeat.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.filebeat.name }}
  labels:
    app: {{ .Values.filebeat.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.filebeat.name }}
  labels:
    app: {{ .Values.filebeat.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.filebeat.name }}
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.filebeat.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
