{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.filebeat.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

          # 템플릿 설정
          templates:
            # 설정된 namespace의 로그만 수집
            - condition:
                and:
                  # 설정된 namespace만 포함
                  - equals:
                      kubernetes.namespace: "{{ .Values.global.namespace }}"
                  # Job Pod 제외
                  - not:
                      or:
                        - contains:
                            kubernetes.pod.name: "elasticsearch-setup"
                        - contains:
                            kubernetes.pod.name: "kibana-setup"
                        - contains:
                            kubernetes.pod.name: "elasticsearch-ca-setup"
              config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  processors:
                    - add_kubernetes_metadata:
                        host: ${NODE_NAME}
                        matchers:
                        - logs_path:
                            logs_path: "/var/log/containers/"

    # 추가 프로세서
    processors:
      # Kubernetes 메타데이터 추가
      - add_cloud_metadata: ~
      - add_host_metadata: ~

      # 불필요한 필드 제거
      - drop_fields:
          fields: ["agent.ephemeral_id", "agent.id", "ecs.version"]
          ignore_missing: true

      # 설정된 namespace가 아닌 로그는 모두 드롭 (이중 안전장치)
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "{{ .Values.global.namespace }}"

    output.logstash:
      hosts: ["{{ .Values.logstash.name }}:{{ .Values.logstash.service.port }}"]
{{- end }}
