{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kibana.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.kibana.name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
      protocol: TCP
      {{- if eq .Values.kibana.service.type "NodePort" }}
      nodePort: {{ .Values.kibana.service.nodePort }}
      {{- end }}
  type: {{ .Values.kibana.service.type }}
{{- end }}
