{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kibana.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kibana.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.kibana.name }}
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.kibana.service.port }}
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              {{- if .Values.elasticsearch.tls.enabled }}
              value: "https://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.service.httpPort }}"
              {{- else }}
              value: {{ .Values.kibana.env.elasticsearchHosts | quote }}
              {{- end }}
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: kibana-password
            {{- if .Values.elasticsearch.tls.enabled }}
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "/usr/share/kibana/config/certs/ca.crt"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "certificate"
            {{- end }}
          {{- if .Values.elasticsearch.tls.enabled }}
          volumeMounts:
            - name: certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
      {{- if .Values.elasticsearch.tls.enabled }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.elasticsearch.name }}-certs
            defaultMode: 0644
      {{- end }}
{{- end }}
