{{- if .Values.logstash.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
  labels:
    app: {{ .Values.logstash.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.logstash.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.logstash.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.logstash.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.logstash.name }}
          image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
          ports:
            - name: beats
              containerPort: {{ .Values.logstash.service.port }}
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.service.httpPort }}"
            - name: ELASTICSEARCH_USERNAME
              value: "logstash_writer"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: logstash-writer-password
            - name: xpack.monitoring.enabled
              value: "false"
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
            {{- if .Values.elasticsearch.tls.enabled }}
            - name: certs
              mountPath: /usr/share/logstash/config/certs
              readOnly: true
            {{- end }}
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline
        {{- if .Values.elasticsearch.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ .Values.elasticsearch.name }}-certs
            defaultMode: 0644
        {{- end }}
{{- end }}