{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.logstash.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  logstash.conf: |
    input {
      beats {
        port => {{ .Values.logstash.service.port }}
      }
    }

    output {
      elasticsearch {
        hosts => ["http://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.service.httpPort }}"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
{{- end }}
