# Development environment values
global:
  namespace: deuknet-dev

elasticsearch:
  enabled: true
  storage:
    size: 5Gi

kibana:
  enabled: true

logstash:
  enabled: true

filebeat:
  enabled: true
