# Production environment values
global:
  namespace: deuknet-prod

app:
  name: deuknet-app
  replicaCount: 3

  image:
    repository: deuknet-app
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP

  env:
    springProfilesActive: prod

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

postgres:
  enabled: true
  env:
    database: deuknet_prod
    username: deuknet_user
    password: CHANGE_ME_PROD_POSTGRES_PASSWORD

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

elasticsearch:
  enabled: true
  env:
    elasticPassword: CHANGE_ME_PROD_ELASTIC_PASSWORD

  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi

kibana:
  enabled: true
  env:
    elasticsearchPassword: CHANGE_ME_PROD_ELASTIC_PASSWORD

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

logstash:
  enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

filebeat:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
