apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  labels:
    app: log-generator
    collect-logs: "true"  # Filebeat가 수집하도록 지정
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh"]
    args: 
      - "-c"
      - |
        echo "Starting log generator..."
        while true; do
          echo "[INFO] Test log message at $(date)"
          echo "[WARN] Warning test message at $(date)"
          echo "[ERROR] Error test message at $(date)"
          sleep 10
        done
  restartPolicy: Always
