apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp # 반드시 deployment.yaml의 metadata.labels.app 과 동일해야 함
  ports:
    - name: http
      port: 80         # 클러스터 내부에서 접근할 포트 (고정 주소)
      targetPort: 8080 # 컨테이너 내부에서 실제 열려 있는 포트
      nodePort: 30080  # (NodePort 타입에서만) 클러스터 외부 접근 포트
  type: NodePort       # Minikube 환경에서 브라우저 접근 가능하게 설정
