app:
  enabled: true
  image:
    repository: localhost:5000/deuknet-app
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  port: 8080
  service:
    type: ClusterIP
    port: 8080

postgres:
  image: postgres:15-alpine
  database: deuknet
  username: deuknet_user
  password: deuknet_pass
  port: 5432

zookeeper:
  image: confluentinc/cp-zookeeper:7.6.0
  port: 2181

kafka:
  image: apache/kafka:3.8.1
  port: 9092
  brokerId: 1

kafkaConnect:
  image: debezium/connect:2.5
  port: 8083
  groupId: 1

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  port: 9200
  javaOpts: "-Xms512m -Xmx512m"

debezium:
  connector:
    name: debezium-postgres-source
    serverName: dbserver1
    slotName: debezium_slot
    tableIncludeList: public.outbox_events

elasticsearchSink:
  connector:
    name: elasticsearch-sink-post-detail
    topics: outbox.events.PostDetail
    indexName: posts-detail
