apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.0
          ports:
            - containerPort: 5044
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "logstash_writer"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: logstash-writer-password
            # Option 1: Disable monitoring (recommended for dev)
            - name: xpack.monitoring.enabled
              value: "false"
            
            # Option 2: Enable monitoring with credentials (uncomment below)
            # - name: xpack.monitoring.enabled
            #   value: "true"
            # - name: xpack.monitoring.elasticsearch.hosts
            #   value: "http://elasticsearch:9200"
            # - name: xpack.monitoring.elasticsearch.username
            #   value: "logstash_system"
            # - name: xpack.monitoring.elasticsearch.password
            #   valueFrom:
            #     secretKeyRef:
            #       name: elasticsearch-credentials
            #       key: logstash-password
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline
